#!/bin/sh
# Cau hinh mac dinh cho SDMC NR3053 co mod USB

# Mui gio Viet Nam
uci set system.@system[0].zonename='Asia/Ho Chi Minh'
uci set system.@system[0].timezone='<+07>-7'
uci commit system

# WAN qua dien thoai Android (USB tethering -> usb0)
if ! uci -q get network.android >/dev/null; then
	uci set network.android=interface
	uci set network.android.proto='dhcp'
	uci set network.android.device='usb0'
	uci set network.android.metric='10'
	uci add_list firewall.@zone[1].network='android'
fi

# WAN qua iPhone (ipheth -> thuong la eth1)
if ! uci -q get network.iphone >/dev/null; then
	uci set network.iphone=interface
	uci set network.iphone.proto='dhcp'
	uci set network.iphone.device='eth1'
	uci set network.iphone.metric='11'
	uci add_list firewall.@zone[1].network='iphone'
fi

uci commit network
uci commit firewall

# Tu khoi dong usbmuxd cho iPhone
[ -x /etc/init.d/usbmuxd ] && /etc/init.d/usbmuxd enable

exit 0
